### ISSUE TITLE
Black screen in Spyder-terminal when I launch Spyer

### ISSUE THREAD

**Issue by h4k1m0u** [spyder-ide/spyder-terminal#130]
## Description of your problem

**What steps will reproduce the problem?**

1. When I launch Spyder.

**What is the expected output? What do you see instead?**
At home on Windows 8, spyder-terminal worked correctly.

**Please provide any additional information below**
![Screenshot on Imgur](https://i.imgur.com/kBZfwSH.png)

## Versions and main components

* Terminal Version: 0.2.3
* Spyder Version: 3.2.7
* Python Version: 3.6.4
* Operating system: Windows 7 x64

**Comment by stonebig** [comment]
it may be related to pywinpty, which has problem under windows 7: 

https://github.com/spyder-ide/pywinpty/pull/90

problem is not solved.

**Comment by ccordoba12** [comment]
And it's unlikely to be solved (because we don't know why that error happens), sorry.

**Comment by andfoy** [comment]
@ccordoba12 Shall we close this one as part of #135 ?

**Comment by ccordoba12** [comment]
Yes, please.

**Comment by Shivambansal97** [comment]
I have a similar problem with spyder 3.3.1 with window 7.if you have fully functional spyder but you can't see the interface try to update the microsoft .net framework to 4.6 or higher.

**Comment by macic385** [comment]
Can somebody please fix this, i have the same issue............

**Comment by IDrei** [comment]
> Can somebody please fix this, i have the same issue............

Did you solve the problem?

**Comment by ccordoba12** [comment]
This should be solved by updating to the latest pywinpty and spyder-terminal.

**Comment by IDrei** [comment]
> This should be solved by updating to the latest pywinpty and spyder-terminal.

It said that all available packages already installed.

This helped:
`conda install -c conda-forge pyhamcrest

python.exe -m pip install --upgrade pip`

**Comment by jungx148** [comment]
I am adding a question since it's not closed yet.

The same problem what h4k1m0u had (Terminal windows is blank as shown in the attached pic) is happening to me and the problem still exists even if I update the latest pywinpty and spyder-terminal.  Also, though I did two suggested updates as IDrei commented, it did not help.

I appreciate all help to solve this problem.

----
[Versions and main components]
Terminal Version: don't know how to check
Spyder Version: 3.3.6
Python Version: 2.7.15
Operating system: Windows 8.1 x64

![error](https://user-images.githubusercontent.com/18514758/62668182-d2edb380-b9c5-11e9-9f5f-bf8ce7df037e.JPG)
